# Url for master node
spark.master                           spark://spark-master:7077 
# Enables Logging of events needed for History server
spark.eventLog.enabled                 true
# Output path for master and worker node events                      
spark.eventLog.dir                     /opt/spark/spark-events
# Input path for history server      
spark.history.fs.logDirectory          /opt/spark/spark-events